sudo: false

language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

cache: apt

addons:
  apt:
    packages:
    - liblapack-dev

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - pip install sklearn>=1.8
  - pip install pytest>=3.0.5
  - pip install pytest-cov>=2.2.1

script:
  - pytest --doctest-glob='README.md' --cov=prince tests/ --verbose

after_success:
  - coveralls
