dist: trusty
sudo: false

language: python

python:
  - "3.5"
  - "3.6"

cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/download

addons:
  apt:
    packages:
      - libc6
      - liblapack-dev

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION --yes
  - source activate testenv
  - pip install --no-binary :all: lightgbm>=2.1.2

install:
  - pip install -r requirements.dev.txt

script:
  - pytest --doctest-glob='docs/*.md' --cov=xam --verbose

after_success:
  - coveralls
